export enum E_FORM_GENERATOR_TYPE {
  INPUT = 'INPUT',
  PASSWORD = 'PASSWORD',
  DATE_PICKER = 'DATE_PICKER',
  SELECT = 'SELECT',
  TEXT_AREA = 'TEXT_AREA',
  CHECKBOX = 'CHECKBOX',
  SWITCH = 'SWITCH'
}
