name: tests

on:
  push:
    branches:
      - development
  pull_request:
    paths:
      - '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn test
